version: "2"
services: 
  port_3306:
    ports:
      - 3306:3306
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - /Users/tao/docker/volum/mysql_5.7:/var/lib/mysql 